export const verifyConstants = {
  VERIFY_REQUEST: 'VERIFY_REQUEST',
  VERIFY_SUCCESS: 'VERIFY_SUCCESS',
  VERIFY_FAILURE: 'VERIFY_FAILURE',
  UPDATE_VERIFY_TOKEN_REQUEST: 'UPDATE_VERIFY_TOKEN_REQUEST',
  UPDATE_VERIFY_TOKEN_SUCCESS: 'UPDATE_VERIFY_TOKEN_SUCCESS',
  UPDATE_VERIFY_TOKEN_FAILURE: 'UPDATE_VERIFY_TOKEN_FAILURE',
};
